"""
export/pdf_exporter.py — HTML → PDF via WeasyPrint (or fallback to reportlab)
"""
from __future__ import annotations

import io
from typing import List
from datetime import datetime

TIER_STYLES = {
    "Reach": {"bg": "#FFF3CD", "text": "#664D03", "badge_bg": "#FF8C00", "badge_text": "#fff"},
    "Match": {"bg": "#D1E7DD", "text": "#0A3622", "badge_bg": "#198754", "badge_text": "#fff"},
    "Safe":  {"bg": "#CFE2FF", "text": "#084298", "badge_bg": "#0D6EFD", "badge_text": "#fff"},
    "Explore": {"bg": "#E2E8F0", "text": "#334155", "badge_bg": "#64748B", "badge_text": "#fff"},
}


def _build_html(entries: list, student_percentile: float, category: str) -> str:
    rows_html = ""
    for entry in entries:
        s = TIER_STYLES[entry.classification]
        rows_html += f"""
        <tr style="background:{s['bg']}; color:{s['text']};">
            <td style="text-align:center; font-weight:bold;">{entry.rank}</td>
            <td><strong>{entry.college_name}</strong><br><small>{entry.district}</small></td>
            <td>{entry.branch_name}</td>
            <td style="text-align:center;">
                <span style="background:{s['badge_bg']};color:{s['badge_text']};
                             padding:2px 8px;border-radius:12px;font-size:10px;font-weight:bold;">
                    {entry.classification.upper()}
                </span>
            </td>
            <td style="text-align:center;">{entry.lower_bound:.1f} – {entry.upper_bound:.1f}</td>
            <td style="text-align:center;">{entry.total_seats}</td>
            <td style="font-size:9px;">{entry.explanation}</td>
        </tr>
        """

    return f"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>CAP Preference List 2025</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: Inter, 'Segoe UI', sans-serif; font-size: 11px; color: #1a1a2e; padding: 20px; }}
  .header {{ background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
             color: white; padding: 20px 24px; border-radius: 8px; margin-bottom: 16px; }}
  .header h1 {{ font-size: 18px; font-weight: 700; margin-bottom: 4px; }}
  .header p {{ font-size: 11px; opacity: 0.8; }}
  .legend {{ display: flex; gap: 16px; margin-bottom: 12px; font-size: 10px; }}
  .badge {{ padding: 3px 10px; border-radius: 12px; font-weight: 600; font-size: 9px; }}
  table {{ width: 100%; border-collapse: collapse; border-radius: 8px; overflow: hidden;
           box-shadow: 0 1px 6px rgba(0,0,0,0.1); }}
  thead tr {{ background: #16213e; color: white; }}
  thead th {{ padding: 10px 8px; text-align: center; font-weight: 600; font-size: 10px; }}
  tbody tr {{ border-bottom: 1px solid rgba(0,0,0,0.06); }}
  tbody td {{ padding: 8px; vertical-align: top; }}
  .footer {{ margin-top: 14px; text-align: center; font-size: 9px; color: #888; }}
</style>
</head>
<body>
<div class="header">
  <h1>CAP Round 2025 — College Preference List</h1>
  <p>
    Student Percentile: <strong>{student_percentile:.2f}</strong> &nbsp;|&nbsp;
    Category: <strong>{category}</strong> &nbsp;|&nbsp;
    Generated: {datetime.now().strftime('%d %b %Y %H:%M')}
  </p>
</div>

<div class="legend">
  <span>Legend:</span>
  <span class="badge" style="background:#FF8C00;color:#fff;">REACH</span> Possible but competitive
  <span class="badge" style="background:#198754;color:#fff;">MATCH</span> Realistic chance
  <span class="badge" style="background:#0D6EFD;color:#fff;">SAFE</span> Very high probability
</div>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>College &amp; District</th>
      <th>Branch</th>
      <th>Type</th>
      <th>Predicted Cutoff Range</th>
      <th>Seats</th>
      <th>Explanation</th>
    </tr>
  </thead>
  <tbody>
    {rows_html}
  </tbody>
</table>

<div class="footer">
  Generated by CAP Preference Advisor · Cutoffs are ML predictions, not official data.
  Always verify with the official DTE Maharashtra portal before final submission.
</div>
</body>
</html>
"""


def generate_pdf(
    entries: list,
    student_percentile: float,
    category: str,
) -> io.BytesIO:
    html = _build_html(entries, student_percentile, category)
    buf = io.BytesIO()

    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html).write_pdf()
        buf.write(pdf_bytes)
    except Exception:
        # Minimal text-based PDF fallback using reportlab
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
            from reportlab.lib.styles import getSampleStyleSheet
            from reportlab.lib import colors

            doc = SimpleDocTemplate(buf, pagesize=A4)
            styles = getSampleStyleSheet()
            story = [
                Paragraph(f"CAP Round 2025 — College Preference List", styles["Title"]),
                Paragraph(f"Percentile: {student_percentile:.2f} | Category: {category}", styles["Normal"]),
                Spacer(1, 12),
            ]

            table_data = [["Rank", "College", "Branch", "Type", "Cutoff Range", "Explanation"]]
            for e in entries:
                table_data.append([
                    str(e.rank), e.college_name[:30], e.branch_code,
                    e.classification, f"{e.lower_bound:.1f}–{e.upper_bound:.1f}",
                    e.explanation[:60],
                ])

            t = Table(table_data, repeatRows=1)
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1A1A2E")),
                ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
                ("FONTSIZE",   (0, 0), (-1, -1), 8),
                ("GRID",       (0, 0), (-1, -1), 0.5, colors.grey),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8F9FA")]),
            ]))
            story.append(t)
            doc.build(story)
        except Exception as e2:
            # Last resort: plain text
            text = f"CAP Preference List\nPercentile: {student_percentile}\n\n"
            for entry in entries:
                text += f"{entry.rank}. {entry.college_name} | {entry.branch_code} | {entry.classification}\n"
            buf.write(text.encode("utf-8"))

    buf.seek(0)
    return buf
